module.exports = {
    A: {ada: "Ada", awk: "Awk"},
    B: {bash: "Bash"},
    C: {c: "c", clj: "Clojure", coffeescript: "CoffeeScript", cpp: "C++", crystal: "Crystal", csharp: "C#", css: "CSS"},
    D: {d: "D", dart: "Dart", delphi: "Delphi", dockerfile: "Dockerfile"},
    E: {elixir: "Elixir", elm: "Elm", erl: "Erlang"},
    F: {fs: "F#"},
    G: {go: "Go", graphql: "GraphQL", groovy: "Groovy"},
    H: {hs: "Haskell", html: "HTML/XML"},
    J: {java: "Java", js: "JavaScript", json: "JSON", julia: "Julia"},
    K: {kt: "Kotlin"},
    L: {latex: "LaTeX", less: "Less", lisp: "Lisp", lua: "Lua"},
    O: {ml: "OCaml"},
    M: {markdown: "Markdown", matlab: "Matlab", mk: "Makefile"},
    N: {nginx: "Nginx", nim: "Nim"},
    P: {perl: "Perl", php: "PHP", powershell: "Powershell", prolog: "Prolog", py: "Python"},
    R: {pl: "Raku", r: "R", rs: "Rust", ruby: "Ruby"},
    S: {sas: "SAS", scala: "Scala", scheme: "Scheme", scss: "SCSS", sql: "SQL", switf: "Swift"},
    T: {tcl: "Tcl", ts: "TypeScript"},
    V: {vbnet: "VB.NET", vhdl: "VHDL"},
    Z: {zsh: "ZSH"},
};